# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages-tron.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'messages-tron.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13messages-tron.proto\"R\n\x0eTronGetAddress\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x17\n\tcoin_name\x18\x02 \x01(\t:\x04Tron\x12\x14\n\x0cshow_display\x18\x03 \x01(\x08\"\x1e\n\x0bTronAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\xca\x01\n\nTronSignTx\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x17\n\tcoin_name\x18\x02 \x01(\t:\x04Tron\x12\x10\n\x08raw_data\x18\x03 \x01(\x0c\x12\x17\n\x0fref_block_bytes\x18\x04 \x01(\x0c\x12\x16\n\x0eref_block_hash\x18\x05 \x01(\x0c\x12\x12\n\nexpiration\x18\x06 \x01(\x04\x12\x15\n\rcontract_type\x18\x07 \x01(\t\x12\x12\n\nto_address\x18\x08 \x01(\t\x12\x0e\n\x06\x61mount\x18\t \x01(\x04\"!\n\x0cTronSignedTx\x12\x11\n\tsignature\x18\x01 \x01(\x0c\x42\x30\n\x1a\x63om.keepkey.deviceprotocolB\x12KeepKeyMessageTron')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_tron_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.keepkey.deviceprotocolB\022KeepKeyMessageTron'
  _globals['_TRONGETADDRESS']._serialized_start=23
  _globals['_TRONGETADDRESS']._serialized_end=105
  _globals['_TRONADDRESS']._serialized_start=107
  _globals['_TRONADDRESS']._serialized_end=137
  _globals['_TRONSIGNTX']._serialized_start=140
  _globals['_TRONSIGNTX']._serialized_end=342
  _globals['_TRONSIGNEDTX']._serialized_start=344
  _globals['_TRONSIGNEDTX']._serialized_end=377
# @@protoc_insertion_point(module_scope)
