# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages-ton.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'messages-ton.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12messages-ton.proto\"\x98\x01\n\rTonGetAddress\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x16\n\tcoin_name\x18\x02 \x01(\t:\x03Ton\x12\x14\n\x0cshow_display\x18\x03 \x01(\x08\x12\x18\n\nbounceable\x18\x04 \x01(\x08:\x04true\x12\x16\n\x07testnet\x18\x05 \x01(\x08:\x05\x66\x61lse\x12\x14\n\tworkchain\x18\x06 \x01(\x11:\x01\x30\"2\n\nTonAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x13\n\x0braw_address\x18\x02 \x01(\t\"\xa2\x01\n\tTonSignTx\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x16\n\tcoin_name\x18\x02 \x01(\t:\x03Ton\x12\x0e\n\x06raw_tx\x18\x03 \x01(\x0c\x12\x11\n\texpire_at\x18\x04 \x01(\r\x12\r\n\x05seqno\x18\x05 \x01(\r\x12\x14\n\tworkchain\x18\x06 \x01(\x11:\x01\x30\x12\x12\n\nto_address\x18\x07 \x01(\t\x12\x0e\n\x06\x61mount\x18\x08 \x01(\x04\" \n\x0bTonSignedTx\x12\x11\n\tsignature\x18\x01 \x01(\x0c\x42/\n\x1a\x63om.keepkey.deviceprotocolB\x11KeepKeyMessageTon')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_ton_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.keepkey.deviceprotocolB\021KeepKeyMessageTon'
  _globals['_TONGETADDRESS']._serialized_start=23
  _globals['_TONGETADDRESS']._serialized_end=175
  _globals['_TONADDRESS']._serialized_start=177
  _globals['_TONADDRESS']._serialized_end=227
  _globals['_TONSIGNTX']._serialized_start=230
  _globals['_TONSIGNTX']._serialized_end=392
  _globals['_TONSIGNEDTX']._serialized_start=394
  _globals['_TONSIGNEDTX']._serialized_end=426
# @@protoc_insertion_point(module_scope)
